### ISSUE TITLE
env若干建议

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/env#136]
- [x] env的menuconfig -s中选择镜像源的注解要清楚的标明使用中国大陆镜像源，防止海外用户误以为是本国加速用的镜像源，gitee选上之后在海外的下载速度会很慢。 https://github.com/RT-Thread/env/pull/137
- [ ] 取消自动递归下载软件包下的submodule功能（软件包gitee同步机器人无力备份submodule，也不需要了，submodule会单独做成一个软件包。目前一旦软件包含有submodule，env就会自动跑到github上去拉去，导致数据断流。）；可以增加一个 pkgs --update-r命令 这个命令是递归submodule的。如果仅是pkgs  --update  则不递归下载submodule
   增加命令 --update-r 表示递归下载submodule
- [x] 增加强制更新本地软件包索引的功能（如果修改本地软件包索引，再更新时会发生合并冲突错误，进而导致更新失败，增加强制更新命令，可以强行覆盖，确保同步最新软件包索引）**社区已经收到N多起类似的问题报告了**  https://club.rt-thread.org/ask/question/434219.html https://github.com/RT-Thread/env/pull/144
- [x] ![image](https://user-images.githubusercontent.com/34888354/155970855-546f8ea9-1ff9-4cab-b2ac-dc3ee3fca114.png) 改成英文
- [x] 显示Scons版本号 通过scons --version 可以显示

**Comment by maikebing** [comment]
linux下看起来没人维护。
