### ISSUE TITLE
关于软件包建议

### ISSUE THREAD

**Issue by maikebing** [RT-Thread/env#154]
1. ~~建议可以选择Gitee 或者Github 下载~~
2. 建议取消使用Gitee的zip下载， 因为gitee需要输入验证码， 基本下载不了。 
3. 可以考虑加入极狐 镜像和 codechina gitlab等。 
4. ~~软件包建议不要跟当前用户 home 目录 写死， 现在写死的方式太麻烦了。 不利于持续集成。~~

**Comment by mysterywolf** [comment]
关于是否使用中国镜像源的问题 使用menuconfig -s命令可以设置

**Comment by maikebing** [comment]
@BernardXiong

**Comment by mysterywolf** [comment]
使用gitee镜像源之后 发布版本是可以正常下载的啊

**Comment by armink** [comment]
> 使用gitee镜像源之后 发布版本是可以正常下载的啊

是的，RTT 的 软件包 是在 gitee 白名单里，可直接下载，无需输入验证码
