### ISSUE TITLE
加强Linux操作系统下ENV的配套建设

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/env#157]

**Comment by BernardXiong** [comment]
这个有什么不同的？Linux下使用env很嗨啊

**Comment by mysterywolf** [comment]
包括文档、视频 尤其是英文的等等，我们自己用的很嗨，也得让开发者用的嗨才行。

**Comment by BernardXiong** [comment]
唔，我还以为是linux下的env有什么bug呐。因为是字符界面的，也许可以出现asc-ii的动画图，这样跟着这个来也就知道怎么用了

**Comment by maikebing** [comment]
Linux 下env  敢不敢  不写死当前用户的 home目录， 有些CI下好麻烦， 总是有遗憾。  @BernardXiong

**Comment by mysterywolf** [comment]
你说的是rtconfig.py下的HOME路径？

**Comment by maikebing** [comment]
脚本里。

**Comment by mysterywolf** [comment]
能给个定位吗？

**Comment by maikebing** [comment]
刚仔细翻了一下代码， 我想我知道问题所在了。 是我的问题。

**Comment by mysterywolf** [comment]
如果有什么好的想法的话 我们的脚本是开源的 欢迎PR
