### ISSUE TITLE
增加zip等文件python下载进度条

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread/env#216]
目前如果一个package是zip文件方式，下载的时候并没有进度信息，需要增加这部分的进度信息情况。

另外，也需要验证package支持tar.gz, tar.bz2等压缩方式，这类主要会在linux上使用。如果涉及到多文件删除，是否也需要加入进度信息情况？这部分可以评估下。

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/env/pull/225

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/env/commit/eb4447938bcf76def2e5d01e89ed39a824ad6ee6
