### ISSUE TITLE
submodule issue

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread/env#65]
当一个package带submodule，而这个package未做镜像功能时，会导致submodule去取镜像的submodule git，但镜像并不存在，而从导致整个packages更新失败

@SummerGGift

**Comment by BernardXiong** [comment]
镜像功能未开启，submodule也失败了

![image](https://user-images.githubusercontent.com/1241087/50380943-7ea2f700-06b4-11e9-86bd-2b3d1a6a547d.png)

**Comment by SummerGGift** [comment]
这个问题我检查一下

**Comment by SummerGGift** [comment]
如果同步运行正常，该模块会在一个小时之内被同步，这时就不会有这个问题了。

**Comment by SummerGGift** [comment]
该问题很早已经修复，可以关闭了。
