### ISSUE TITLE
建议在pkgs文件或env.py中指定python版本

### ISSUE THREAD

**Issue by Sth32** [RT-Thread/env#94]
在manjaro下，我使用pkgs命令时出现如下报错
```
$pkgs --update
  File "/home/sth32/.env/tools/scripts/env.py", line 74
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```
有的linux发行版将python3作为默认的python
使用`python2 ~/.env/tools/scripts/env.py package $*`可以防止此类问题出现

**Comment by SummerGGift** [comment]
后续会逐渐兼容 python3

**Comment by SummerGGift** [comment]
兼用 python2 和 python3 的 PR 已经提交了。

**Comment by SummerLife** [comment]
更新到新版后，该问题已经不存在的，ISSUE 可以关闭了 @armink
